# Arrays in NumPy

In [1]:
import numpy as np

## Creating a NumPy array

Three lists, one for GK heights, one for GK weights, one for names

In [2]:
gk_names = ['Kaller', 'Fradeel', 'Hayward', 'Honeyman']
gk_heights = [184, 188, 191, 193]
gk_weights = [81, 85, 103, 99]

Create an array of names

In [3]:
print(np.array(gk_names))

['Kaller' 'Fradeel' 'Hayward' 'Honeyman']


Create a matrix of all three lists, start with a list of lists

In [4]:
gk_matrix = [gk_names, gk_heights, gk_weights]
print(np.array(gk_matrix))

[['Kaller' 'Fradeel' 'Hayward' 'Honeyman']
 ['184' '188' '191' '193']
 ['81' '85' '103' '99']]


With 'arange', we can create arrays just like we created lists with 'range'

This gives us an array ranging from the numbers in the arguments

In [5]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Want a blank array? Create it full of zeroes with 'zeros'

The argument within it create the shape of a 2d or 3d array

In [6]:
np.zeros((3,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Hate zeros? why not use 'ones'?

In [7]:
np.ones((3,11))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Creating dummy data or need a random number? `randint` and `randn` are useful here.

Creates random numbers around a standard distribution from 0

The argument gives us the array's shape


In [8]:
print(np.random.randn(3,3))

[[-0.37465564 -1.25273583  0.1746015 ]
 [ 0.43389693 -0.82725396 -0.6389055 ]
 [ 0.75459955 -1.18671768 -0.80882093]]


Creates random numbers between two nubmers that we give it.

The third argument gives us the shape of the array

In [9]:
print(np.random.randint(1,100,(3,3)))

[[59 35 91]
 [ 9 62 10]
 [ 9 18 45]]


## Array Methods

Three lists, one for GK heights, one for GK weights, one for names.

Create an array with each list (done above near the top).

In [11]:
np.array(gk_names)
gk_heights = np.array(gk_heights)
np.array(gk_weights)

array([ 81,  85, 103,  99])


What is the largest height, `.max()`?

In [12]:
gk_heights.max()

193

What location is the max, `.argmax()`?

In [13]:
gk_heights.argmax()

3

Can I use this method to locate the player's name?

Instead of a number in the square brackets, I can just put this method:

In [14]:
gk_names[gk_heights.argmax()]

'Honeyman'

With only four players, this is a big long-winded, but I'm sure that you can see the benefit if we have a whole academy of players and we need to find our tallest player from 100s. Swap the max to min to find the smallest value in an array.

In [15]:
gk_names[gk_heights.argmin()]

'Kaller'